 export const horario = [
    { label: '09:00 am'},
    { label: '09:30 am'},
    { label: '10:00 am'},
    { label: '10:30 am'},
    { label: '11:00 am'},
    { label: "11:30 am"},
    { label: '12:00 pm'},
    { label: '12:30 pm'},
    { label: '13:00 pm'},
    { label: '13:30 pm'},
    { label: '14:00 pm'},
    { label: '14:30 pm'},
    { label: '15:00 pm'},
    { label: '15:30 pm'},
    { label: '16:00 pm'},
    { label: '16:30 pm'},
    { label: '17:00 pm'},
    { label: '17:30 pm'},
    { label: '18:00 pm'},
];

export const pagamento = [
    { label: 'Cartão de Crédito'},
    { label: 'Cartão de Débito'},
    { label: 'Dinheiro'},
    { label: 'Pix'},
    { label: 'Boleto'},
    { label: "Paypal"},
    { label: 'Mercado Pago'},
    { label: 'Crédito Loja'},
];